Feat: 댓글 생성 기능 구현
prgrms-web-devcourse/Team-07-hey-cake-BE pull request #104
Opened 2023-03-03 17:12 UTC by rhdtn311

### 🐕 작업 개요
- closed #101 

### ⚒️ 작업 사항
- 댓글 생성 기능을 구현하였습니다.

### 📚 참고 자료

### 🧐 고민 해줬으면 하는 점

2023-03-03 18:07 UTC, goseungwon approved these changes
고생하셨습니다!!!
한가지 코멘트 남겼습니다 :)

2023-03-03 18:07 UTC, goseungwon commented on src/main/java/com/programmers/heycake/domain/comment/service/CommentService.java
> +
하나의 service에서 3개의 repository를 보는게 어색하다 느껴집니다 🤓

2023-03-04 06:41 UTC, BnDC approved these changes
고생하셨습니다~

2023-03-04 17:08 UTC, Seongjun-Kwon requested changes

2023-03-04 17:08 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/heycake/domain/market/model/entity/Market.java
> +	}
Member 엔티티에 있는것이 더 자연스럽지 않을까요?

2023-03-04 17:08 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/heycake/domain/order/model/entity/Order.java
> +	}
사용하게되면 order.isNotWriter 형식으로 쓰여질텐데 메서드 네이밍이 어색한 것 같아요

2023-03-04 18:22 UTC, rhdtn311 commented on src/main/java/com/programmers/heycake/domain/comment/service/CommentService.java
> +
> 하나의 service에서 3개의 repository를 보는게 어색하다 느껴집니다 🤓
문제점이 딱히 떠오르지 않는데 혹시 어떤 문제가 있을까요 ??

2023-03-04 18:36 UTC, rhdtn311 commented on src/main/java/com/programmers/heycake/domain/market/model/entity/Market.java
> +	}
수정했습니다.

2023-03-04 19:15 UTC, rhdtn311 commented on src/main/java/com/programmers/heycake/domain/order/model/entity/Order.java
> +	}
> 사용하게되면 order.isNotWriter 형식으로 쓰여질텐데 메서드 네이밍이 어색한 것 같아요

수정했습니다.

2023-03-04 19:23 UTC, goseungwon commented on src/main/java/com/programmers/heycake/domain/comment/service/CommentService.java
> +
저도 당장의 문제는 없다 생각해요 근데 서비스는 각 레포지토리만 의존하고 퍼사드에서 조합하는게 좋다고 생각해요

2023-03-04 19:52 UTC, Seongjun-Kwon approved these changes
고생하셨어요

2023-03-04 19:52 UTC, merged