Test: 주문 상세 조회 API 테스트
prgrms-web-devcourse/Team-07-hey-cake-BE pull request #238
Opened 2023-03-11 15:10 UTC by BnDC

### 🐕 작업 개요
- close #237 

### ⚒️ 작업 사항
- 주문 상세 조회 API 테스트

2023-03-11 20:41 UTC, rhdtn311 requested changes
- 상세 조회가 2개인 것 같아서 확인 부탁드립니다. 
- 값 검증은 안해도 될까요? 특히나 조회라 필요할 것 같긴합니다. 예를들어 주문 상세 조회에서 `offerCount`가 2여야 되는데 0으로 조회되면 이 테스트에선 검증할 수 없을 것 같습니다.

2023-03-11 20:41 UTC, rhdtn311 commented on src/test/java/com/programmers/heycake/domain/order/controller/OrderControllerTest.java
> +
이거 제거하고 class 단에도 `@Transactional`을 붙이면 될 것 같습니다.

2023-03-11 20:41 UTC, rhdtn311 commented on src/test/java/com/programmers/heycake/domain/order/controller/OrderControllerTest.java
> +		@DisplayName("Success - Order 상세 조회 성공")
리스트 조회인 것 같습니다. 그리고 `@Nested` 아래 `@DisplayName`에는 주문, 여기는 `Order`라고 적은 이유가 있나요?

2023-03-11 20:41 UTC, rhdtn311 commented on src/test/java/com/programmers/heycake/domain/order/controller/OrderControllerTest.java
> +			mockMvc.perform(get("/api/v1/orders/{orderId}", order.getId()))
`@Nested` 쪽 보면 리스트 조회인 것 같은데 아래 상세 조회랑 완전히 중복된 테스트 같습니다.

2023-03-12 09:25 UTC, BnDC commented on src/test/java/com/programmers/heycake/domain/order/controller/OrderControllerTest.java
> +			mockMvc.perform(get("/api/v1/orders/{orderId}", order.getId()))
그러네요 주문 상세 조회를 기반으로 주문 리스트 조회 테스트를 작성하고 있던것이 같이 올라갔군요 ㅠㅠ

2023-03-12 09:26 UTC, BnDC commented on src/test/java/com/programmers/heycake/domain/order/controller/OrderControllerTest.java
> +		@DisplayName("Success - Order 상세 조회 성공")
주문으로 통일하는 것이 좋아보입니다

2023-03-12 09:26 UTC, BnDC commented on src/test/java/com/programmers/heycake/domain/order/controller/OrderControllerTest.java
> +
class단에 `@Transactional` 을 붙이면 된다는 것이 `OrderControllerTest` 위에 붙이라는 말씀이실까요?

2023-03-12 10:39 UTC, goseungwon reviewed
고생하셨습니다!! 코멘트 확인해주세요!

2023-03-12 10:39 UTC, goseungwon commented on src/test/java/com/programmers/heycake/domain/order/controller/OrderControllerTest.java
> +	}
중복같군요

2023-03-12 12:22 UTC, rhdtn311 commented on src/test/java/com/programmers/heycake/domain/order/controller/OrderControllerTest.java
> +
> class단에 `@Transactional` 을 붙이면 된다는 것이 `OrderControllerTest` 위에 붙이라는 말씀이실까요?

넵

2023-03-12 14:56 UTC, Seongjun-Kwon approved these changes
고생하셨습니다. 다른 분들이 해주신 리뷰가 많아서 더 할 이야기가 없네요!

2023-03-12 19:26 UTC, BnDC commented on src/test/java/com/programmers/heycake/domain/order/controller/OrderControllerTest.java
> +
제안해주신대로 바꾸면 어떤 장점이 있을까요?

2023-03-13 06:01 UTC, rhdtn311 approved these changes
👍

2023-03-13 06:03 UTC, goseungwon approved these changes

2023-03-13 06:19 UTC, merged