Test: 오퍼 목록 조회 테스트
prgrms-web-devcourse/Team-07-hey-cake-BE pull request #243
Opened 2023-03-11 19:55 UTC by rhdtn311

### 🐕 작업 개요
- closed #241 

### ⚒️ 작업 사항
- 오퍼 목록 조회 테스트 코드를 작성했습니다.

### 📚 참고 자료

### 🧐 고민 해줬으면 하는 점

2023-03-12 10:45 UTC, goseungwon approved these changes
고생하셨습니다~

2023-03-12 15:04 UTC, Seongjun-Kwon approved these changes
고생하셨습니다. 빛이 나네요

2023-03-12 15:04 UTC, Seongjun-Kwon commented on src/test/java/com/programmers/heycake/domain/offer/controller/OfferControllerTest.java
> +		}
👍

2023-03-12 19:02 UTC, BnDC requested changes
고생하셨습니다~

2023-03-13 07:51 UTC, BnDC approved these changes
👍

2023-03-13 08:00 UTC, merged