Refactor: 리프레시 토큰에 레디스 도입
prgrms-web-devcourse/Team-07-hey-cake-BE pull request #305
Opened 2023-04-03 15:34 UTC by BnDC

### 🐕 작업 개요
- close #303 

### ⚒️ 작업 사항
- `refreshtoken`에 redis 도입
- 컨벤션 수정에 맞춰 `tokenService`에서 Token entity 반환 하도록 수정
- 변경으로 인한 테스트 수정
- Token에 `accessToken` 추가

### 📚 참고 자료
https://hudi.blog/refresh-token-in-spring-boot-with-redis/

2023-04-04 16:03 UTC, goseungwon requested changes
고생하셨습니다!!!
추후에 성능테스트를 진행할 때 Redis client마다 비교하면 재밌을 것 같아요

2023-04-04 16:03 UTC, goseungwon commented on docker/docker-compose.yml
> +    image: redis:latest
일전에 제가 피드백 받았었는데 latest보다 버전 명시가 더 명확하다고 생각합니다.

2023-04-04 16:03 UTC, goseungwon commented on docker/docker-compose.yml
> +    container_name: hey-cake-redis
운영환경과 분리하지 않은 이유가 있을까요?

2023-04-04 16:03 UTC, goseungwon commented on src/main/java/com/programmers/heycake/common/config/RedisConfig.java
> +
전역변수로 관리하는게 더 안전해 보입니다

2023-04-05 06:06 UTC, BnDC commented on src/main/java/com/programmers/heycake/common/config/RedisConfig.java
> +
수정하겠습니다.

2023-04-05 06:07 UTC, BnDC commented on docker/docker-compose.yml
> +    container_name: hey-cake-redis
운영서버의 환경과 개발 서버의 환경이 다르지 않기 때문입니다.
운영서버와 개발 서버 각각의 EC2의 내부에서 redis-server를 설치해서 사용합니다.

2023-04-05 06:09 UTC, BnDC commented on docker/docker-compose.yml
> +    image: redis:latest
아직 서버에 redis가 설치되지 않아서, 개발시 임시로 `latest`를 사용했었는데요 
설치되는 버전에 맞게 수정하겠습니다.

2023-04-05 08:42 UTC, rhdtn311 approved these changes
👍

2023-04-05 10:52 UTC, goseungwon approved these changes

2023-04-05 18:16 UTC, Seongjun-Kwon approved these changes
고생하셨습니다~

2023-04-05 18:16 UTC, Seongjun-Kwon commented on .github/workflows/cd.yml
> +            ${{ runner.os }}-gradle-
탭 간격이 팀원들이랑 좀 다른 것 같아요

2023-04-05 18:16 UTC, Seongjun-Kwon commented on .github/workflows/ci.yml
> +            ~/.gradle/wrapper
탭 간격 여기도요. 한번 확인해주세요

2023-04-06 16:42 UTC, BnDC commented on .github/workflows/cd.yml
> +            ${{ runner.os }}-gradle-
팀원들이랑 탭간격이 동일한 것을 확인하였습니다. 저 부분은 작성될 때, 인위적으로 스페이스가 들어갔는데,
이번 코드 수정하면서 ctrl + alt + l 자동 서식 완성하여 수정된거 같습니다.

2023-04-06 16:42 UTC, BnDC commented on .github/workflows/ci.yml
> +            ~/.gradle/wrapper
위와 같습니다

2023-04-06 16:48 UTC, merged