Feat: 업체 팔로우 신청/취소 API 구현
prgrms-web-devcourse/Team-07-hey-cake-BE pull request #308
Opened 2023-04-04 11:42 UTC by goseungwon

### 🐕 작업 개요
- close #306 

### ⚒️ 작업 사항
- 팔로우 생성/삭제 API 추가
- 팔로우 생성/삭제 테스트 코드 추가
- restDocs에 추가

2023-04-05 15:31 UTC, BnDC approved these changes
고생하셨습니다~

2023-04-05 15:31 UTC, BnDC commented on src/main/java/com/programmers/heycake/domain/member/controller/FollowController.java
> +@Validated
`@PathVariable`의 `Bean Validation`을 동작시키기 위함인가요?

2023-04-05 15:31 UTC, BnDC commented on src/test/java/com/programmers/heycake/domain/member/controller/FollowControllerTest.java
> +							.header("access_token", ACCESS_TOKEN)
인증실패를 가정하면 잘못된 토큰이 들어가거나 아애 없어야 하지 않나요?

2023-04-05 15:31 UTC, BnDC commented on src/test/java/com/programmers/heycake/domain/member/controller/FollowControllerTest.java
> +			mockMvc.perform(delete("/api/v1/follows/{marketId}", market.getId())
follow를 하는 api와 삭제하는 api를 다 호출하는 이유가 있을까요??
follow를 repository로 직접 주입하는 방법이 없어서 일까요? 삭제 테스트가 생성에도 종속되는 느낌입니다.

2023-04-05 15:31 UTC, BnDC commented on src/test/java/com/programmers/heycake/domain/member/controller/FollowControllerTest.java
> +							.header("access_token", ACCESS_TOKEN)
위와 같이 유효하지 않은 `access_token`을 넣어 주거나 `token`이 없어야 할 거 같습니다.

2023-04-05 19:13 UTC, Seongjun-Kwon approved these changes
고생하셨습니다

2023-04-05 19:13 UTC, Seongjun-Kwon commented on docker/init.sql
> +      deleted_at	TIMESTAMP	NULL
다른 엔티티들은 datetime(6) 을 이용하고 있습니당

2023-04-05 19:13 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/heycake/domain/facade/FollowFacade.java
> +		existMarket(marketId);
메서드 명에 체크한다는 의미가 있으면 더 직관적일 것 같아요

2023-04-05 19:13 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/heycake/domain/member/controller/FollowController.java
> +@Validated
저는 @PathVariable 에 @Positive 을 써서 클래스 단에 Validated 를 붙이기보다는
Long marketId 같은 경우는 음수가 들어오면 어차피 EntityNotFound 로 처리되니 따로 @Positive 처리를 해주지 않았습니다.
코드 통일감 때문에 이 방식을 선호하였는데 승원님 생각은 어떠신지요?

2023-04-05 19:13 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/heycake/domain/member/controller/FollowController.java
> +	@PostMapping("{marketId}")
``` suggestion
@PostMapping("/{marketId}")
```

앞에 슬래시가 빠진 것 같네용

2023-04-05 19:13 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/heycake/domain/member/controller/FollowController.java
> +	@DeleteMapping("{marketId}")
여기도 슬래시 빠진 것 같네용

2023-04-06 08:54 UTC, rhdtn311 requested changes

2023-04-06 08:54 UTC, rhdtn311 commented on docker/init.sql
> +      member_id	BIGINT	NOT NULL,
`member_id`, `market_id` 유니크키 제약조건이 있으면 좋을 것 같습니다.

2023-04-06 08:54 UTC, rhdtn311 commented on docker/init.sql
> +      market_id	BIGINT	NOT NULL,
member_id, market_id에 외래키 제약 조건을 뺀 이유가 있을까요?

2023-04-06 08:54 UTC, rhdtn311 commented on src/main/java/com/programmers/heycake/domain/facade/FollowFacade.java
> +			throw new BusinessException(ErrorCode.BAD_REQUEST);
`EntityNotFound` 대신 `BadRequest`를 사용한 이유가 있을까요?

2023-04-06 08:59 UTC, rhdtn311 approved these changes
고생하셨습니다~

근데 한 가지 궁금한 점이 있는데 팔로우 추가/팔로우 취소 버튼이 따로 있는건가요? 아니면 팔로우 버튼만 있고 이미 팔로우 한 상대를 팔로우하면 팔로우 취소 api가 호출되고, 팔로우 한 대상이 아닌 경우 팔로우 버튼을 누르면 팔로우 추가 api가 호출되는 건가요? 만약 후자라면 업체 정보를 조회할 때 회원이 팔로우를 했는지 안했는지에 대한 정보도 같이 프론트에 보내줘야 할 것 같습니다.

2023-04-06 14:06 UTC, Seongjun-Kwon approved these changes
고생하셨습니다

2023-04-06 14:32 UTC, goseungwon commented on src/main/java/com/programmers/heycake/domain/member/controller/FollowController.java
> +@Validated
> @PathVariable의 Bean Validation을 동작시키기 위함인가요?

맞습니다!!!

2023-04-06 14:34 UTC, goseungwon commented on src/main/java/com/programmers/heycake/domain/member/controller/FollowController.java
> +@Validated
> 저는 @PathVariable 에 @positive 을 써서 클래스 단에 Validated 를 붙이기보다는
Long marketId 같은 경우는 음수가 들어오면 어차피 EntityNotFound 로 처리되니 따로 @positive 처리를 해주지 않았습니다.
코드 통일감 때문에 이 방식을 선호하였는데 승원님 생각은 어떠신지요?

코드 통일감은 저도 전적으로 동의 합니다. 성준님 말씀대로 어차피 조회할 때 예외처리가 될테니까요
저는 `BadRequest`와 `EntityNotFound`는 완전히 다르다고 생각해서 분리를 했습니다. 팀적으로 논의 후 컨벤션을 만드는게 좋을 것 같아요

2023-04-06 14:36 UTC, goseungwon commented on src/test/java/com/programmers/heycake/domain/member/controller/FollowControllerTest.java
> +							.header("access_token", ACCESS_TOKEN)
맞습니다. 하지만 restDocs에 `access_token`에 대해 보여주기 위해서 토큰은 담았습니다.
SecurityContext에 값을 넣지 않아서 토큰이 없는 것 처럼 테스트 했습니다.

2023-04-06 14:40 UTC, goseungwon commented on src/test/java/com/programmers/heycake/domain/member/controller/FollowControllerTest.java
> +			mockMvc.perform(delete("/api/v1/follows/{marketId}", market.getId())
아무래도 삭제기 때문에 종속은 필연적이라고 생각해서 이와같이 작성했습니다.
주형님 말씀대로 repository를 사용 한다면 종속성이 조금 줄어들거라고 생각이 드는군요.
제가 잘이해 한 걸까요?

2023-04-06 14:44 UTC, goseungwon commented on docker/init.sql
> +      deleted_at	TIMESTAMP	NULL
변경했습니다.

2023-04-06 14:46 UTC, goseungwon commented on src/main/java/com/programmers/heycake/domain/member/controller/FollowController.java
> +	@PostMapping("{marketId}")
반영했습니다

2023-04-06 14:47 UTC, goseungwon commented on docker/init.sql
> +      member_id	BIGINT	NOT NULL,
복합키로 만든 뒤 유니크하게 관리하라는 말씀이신가요?

2023-04-06 15:31 UTC, goseungwon commented on docker/init.sql
> +      market_id	BIGINT	NOT NULL,
깜빡했습니다.. 추가했습니다.

2023-04-06 16:07 UTC, goseungwon commented on src/main/java/com/programmers/heycake/domain/facade/FollowFacade.java
> +			throw new BusinessException(ErrorCode.BAD_REQUEST);
잘못된 입력이라고 생각해서 BadRequest를 반환했습니다. 지금 생각하니까 ENF가 맞는거같아요

2023-04-06 16:09 UTC, BnDC commented on src/test/java/com/programmers/heycake/domain/member/controller/FollowControllerTest.java
> +							.header("access_token", ACCESS_TOKEN)
그러면 정상적인 값과 차이를 두기 위해 `ACCESS_TOKEN` 이 아닌 `INVALID_ACCESS_TOKEN` 값을 넣어 주는게 좋을거 같습니다.

2023-04-06 16:12 UTC, BnDC commented on src/test/java/com/programmers/heycake/domain/member/controller/FollowControllerTest.java
> +			mockMvc.perform(delete("/api/v1/follows/{marketId}", market.getId())
넵 맞아요. 삭제 테스트인데 생성이 잘못되면, 삭제와 관련 없이 테스트가 깨지게 됩니다. 삭제 테스트가 생성 테스트에 의존하게 되어 생성과 관련없이, repository로 넣어 주는 방식이 더 좋을 거 같다는 의견이었습니다.

2023-04-06 16:20 UTC, goseungwon commented on src/main/java/com/programmers/heycake/domain/facade/FollowFacade.java
> +		existMarket(marketId);
변경했습니다~

2023-04-06 16:21 UTC, goseungwon commented on src/test/java/com/programmers/heycake/domain/member/controller/FollowControllerTest.java
> +							.header("access_token", ACCESS_TOKEN)
위에서 얘기하시죠 :)

2023-04-06 16:21 UTC, goseungwon commented on src/test/java/com/programmers/heycake/domain/member/controller/FollowControllerTest.java
> +							.header("access_token", ACCESS_TOKEN)
이미 ACCESS_TOKEN도 유효하지 않은 값인데도 구분하는게 좋을까요?

2023-04-06 16:39 UTC, goseungwon commented on src/test/java/com/programmers/heycake/domain/member/controller/FollowControllerTest.java
> +			mockMvc.perform(delete("/api/v1/follows/{marketId}", market.getId())
수정했습니다!

2023-04-06 16:40 UTC, goseungwon commented
> 고생하셨습니다~
> 
> 근데 한 가지 궁금한 점이 있는데 팔로우 추가/팔로우 취소 버튼이 따로 있는건가요? 아니면 팔로우 버튼만 있고 이미 팔로우 한 상대를 팔로우하면 팔로우 취소 api가 호출되고, 팔로우 한 대상이 아닌 경우 팔로우 버튼을 누르면 팔로우 추가 api가 호출되는 건가요? 만약 후자라면 업체 정보를 조회할 때 회원이 팔로우를 했는지 안했는지에 대한 정보도 같이 프론트에 보내줘야 할 것 같습니다.

후자입니다. 업체 상세를 볼 때 follow 유무도 확인해야되겠군요.. 그부분은 확인하지 못했습니다. 감사합니다

2023-04-10 09:04 UTC, rhdtn311 commented on docker/init.sql
> +      member_id	BIGINT	NOT NULL,
> 복합키로 만든 뒤 유니크하게 관리하라는 말씀이신가요?

https://myhappyman.tistory.com/148

2023-04-10 09:25 UTC, BnDC commented on src/test/java/com/programmers/heycake/domain/member/controller/FollowControllerTest.java
> +							.header("access_token", ACCESS_TOKEN)
성공 응답의 경우 요청에 `ACCESS_TOKEN`을 유효한 토큰이라고 가정하고 넣어 주신 것이 아닌지요.

어떤 요청에는 `ACCESS_TOKEN`을 넣어 주었는데, 성공 응답이 나오고, 
다른 요청에는 같은 `ACCESS_TOKEN`을 넣어주었는데, 
실패 응답을 반환하는 것은 읽는 사람으로 하여금 혼동의 여지를 주는 거 같습니다.

`ACCESS_TOKEN`과 `INVAID_ACCESS_TOKEN`을 명시적으로 나누면,
어떤것이 유효한 토큰이고, 잘못된 토큰인지 직관적으로 이해 될 거 같습니다.

테스트는 명세로서의 역할을 한다고 했을 때, 코드를 읽는 사람으로 하여금 
개인적으로 후자가 더 좋지 않을 까 하는 생각에 제안을 드렸습니다.

2023-04-10 10:58 UTC, goseungwon commented on src/test/java/com/programmers/heycake/domain/member/controller/FollowControllerTest.java
> +							.header("access_token", ACCESS_TOKEN)
> ACCESS_TOKEN과 INVAID_ACCESS_TOKEN을 명시적으로 나누면,
어떤것이 유효한 토큰이고, 잘못된 토큰인지 직관적으로 이해 될 거 같습니다.
테스트는 명세로서의 역할을 한다고 했을 때, 코드를 읽는 사람으로 하여금
개인적으로 후자가 더 좋지 않을 까 하는 생각에 제안을 드렸습니다.

제가 rest docs 결과물 관점에서만 생각했군요. 코드로도 이해할 수 있어야 하는데,,
수정했습니다.

2023-04-10 11:38 UTC, merged