Feat: 업체 선택 완료 API 구현
prgrms-web-devcourse/Team-07-hey-cake-BE pull request #49
Opened 2023-02-26 15:41 UTC by goseungwon

### 🐕 작업 개요
- close #47 

### ⚒️ 작업 사항
- OrderHistory 관련 DTO 생성
- OrderHistory 생성 API 구현 
- OrderHistory 생성 API 테스트 코드 작성
- Offer조회시 fetch join 사용하도록 구현

### 🧐 고민 해줬으면 하는 점
- 통합테스트에서 order와 offer 생성 코드가 아직 없어서 완료하지 못했습니다. 추후에 완료하도록 하겠습니다.
- Offer 쪽 제가 맡은 코드가 아닌데 필요해서 일단 만들어봤습니다. 생성코드가 생긴다면 테스트 코드도 작성하도록 하겠습니다.

2023-02-27 04:37 UTC, Seongjun-Kwon requested changes

2023-02-27 04:37 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/heycake/common/mapper/HistoryMapper.java
> +	public static OrderHistory toOrderHistory(HistoryRequest historyRequest) {
toEntity 가 아니라 to엔티티이름 이었군요
DTO 의 경우는 toResponse, 이런 네이밍이었죠?

2023-02-27 04:37 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/heycake/domain/offer/repository/OfferRepository.java
> +	Optional<Offer> findById(Long offerId);
fetch join 을 해준다는 걸 명시해주면 좋을 것 같아요 👍

2023-02-27 04:37 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/heycake/domain/offer/service/OfferService.java
> +	public Offer findById(Long offerId) {
빈 값이 올 일이 없으니 get ~ 으로 네이밍을 하는 것은 어떨까요?

https://creampuffy.tistory.com/162
https://tuhrig.de/find-vs-get/

2023-02-27 04:37 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/heycake/domain/order/model/vo/request/HistoryControllerRequest.java
> +		@NotBlank
Long 이기에 @NotBlank 보다는 @NotNull 이 적절할 것 같아요 👍

2023-02-27 04:37 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/heycake/domain/order/model/vo/request/HistoryControllerRequest.java
> +		@NotBlank
여기도 위와 같습니다.

2023-02-27 04:37 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/heycake/domain/order/facade/HistoryFacade.java
> +		// DTO로 변경
👍

2023-02-27 04:37 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/heycake/domain/order/model/vo/request/HistoryRequest.java
> +) {
HistoryContollerRequest 랑 역할의 차이가 명시되면 좋을 것 같아요

2023-02-27 04:37 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/heycake/domain/order/service/HistoryService.java
> +	}
``` suggestion
public Long createHistory(HistoryRequest historyRequest) {
  History history = toOrderHistory(historyRequest)
  return historyRepository.save(history).getId();
}
```
좀 더 보기 편할 것 같아서 남겨봅니다 👍

2023-02-27 04:37 UTC, Seongjun-Kwon commented on src/test/java/com/programmers/heycake/domain/order/controller/HistoryControllerTest.java
> +		@DisplayName("Success - orderHistory 를 생성한다. - createHistory")
Nested 하위 테스트들은 맨 마지막에 메서드명을 적어주지 않습니다 👍

2023-02-27 04:37 UTC, Seongjun-Kwon commented on src/test/java/com/programmers/heycake/domain/order/controller/HistoryControllerTest.java
> +							// 		.headers("access_token", "asdfad")
👍

2023-02-27 04:37 UTC, Seongjun-Kwon commented on src/test/java/com/programmers/heycake/domain/order/facade/HistoryFacadeTest.java
> +			verify(historyService).createHistory(any(HistoryRequest.class));
void 반환 값이라 따로 stub 을 안해주셨군요! 👍

2023-02-27 04:37 UTC, Seongjun-Kwon commented on src/test/java/com/programmers/heycake/domain/order/service/HistoryServiceTest.java
> +		@DisplayName("Success - orderHistory 를 생성한다. - createHistory")
여기도 위에 말씀드린 컨벤션입니다

2023-02-27 04:40 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/heycake/common/mapper/HistoryMapper.java
> +public class HistoryMapper {
mapper 는 static 메서드만 있으니 Mapper 클래스 인스턴스 생성을 막는건 어떨까요?

2023-02-27 08:08 UTC, goseungwon commented on src/main/java/com/programmers/heycake/common/mapper/HistoryMapper.java
> +	public static OrderHistory toOrderHistory(HistoryRequest historyRequest) {
저는 to + 변환하려는 객체 이름이라 생각했어요

2023-02-27 08:08 UTC, goseungwon commented on src/main/java/com/programmers/heycake/common/mapper/HistoryMapper.java
> +	public static OrderHistory toOrderHistory(HistoryRequest historyRequest) {
동기화가 필요할것 같군요

2023-02-27 08:12 UTC, goseungwon commented on src/main/java/com/programmers/heycake/domain/offer/repository/OfferRepository.java
> +	Optional<Offer> findById(Long offerId);
``` java
Optional<Offer> findByIdWithFetchJoin(Long offerId);
```
로 변경했습니다!

2023-02-27 08:13 UTC, goseungwon commented on src/main/java/com/programmers/heycake/domain/offer/service/OfferService.java
> +	public Offer findById(Long offerId) {
변경했습니다~

2023-02-27 08:17 UTC, goseungwon commented on src/main/java/com/programmers/heycake/domain/order/model/vo/request/HistoryRequest.java
> +) {
`HistoryFacadeRequest` 로 변경했습니다. service 에서도 사용해서 네이밍하기 애매해서 포괄적으로 사용했었어요

2023-02-27 08:21 UTC, goseungwon commented on src/test/java/com/programmers/heycake/domain/order/facade/HistoryFacadeTest.java
> +			verify(historyService).createHistory(any(HistoryRequest.class));
네 맞습니다

2023-02-27 08:22 UTC, goseungwon commented on src/main/java/com/programmers/heycake/common/mapper/HistoryMapper.java
> +public class HistoryMapper {
제가 깜빡했군요 !
`@NoArgsConstructor(access = AccessLevel.PRIVATE)` 추가했습니다

2023-03-02 16:31 UTC, Seongjun-Kwon approved these changes
고생많으셨습니다 승원님
근사한 코드에 눈이 부십니다

2023-03-02 17:23 UTC, BnDC approved these changes
고생하셨습니다~

2023-03-02 17:23 UTC, BnDC commented on src/main/java/com/programmers/heycake/domain/order/service/HistoryService.java
> +	}
이 부분은 개인적인 선호도 영역인거 같아요😸 저는 전자가 더 깔끔하게 느껴집니다

2023-03-02 17:31 UTC, goseungwon commented on src/main/java/com/programmers/heycake/domain/order/service/HistoryService.java
> +	}
이런 토론 재밌어요

2023-03-03 08:47 UTC, rhdtn311 approved these changes
고생하셨습니다.

2023-03-03 08:47 UTC, rhdtn311 commented on src/main/java/com/programmers/heycake/domain/offer/repository/OfferRepository.java
> +	Optional<Offer> findByIdWithFetchJoin(Long offerId);
연관된 어떤 엔티티를 함께 패치 해오는지 메서드 명에 명시하면 좋을 것 같아요.

2023-03-03 08:47 UTC, rhdtn311 commented on src/main/java/com/programmers/heycake/domain/order/service/OrderService.java
> +	private Order getEntity(Long orderId) {
`getOrder`가 더 명확한 것 같습니다.

2023-03-03 08:53 UTC, goseungwon commented on src/main/java/com/programmers/heycake/domain/order/service/OrderService.java
> +	private Order getEntity(Long orderId) {
반영했습니다

2023-03-03 09:02 UTC, merged