Feature/ 제안 생성 API 구현
prgrms-web-devcourse/Team-07-hey-cake-BE pull request #53
Opened 2023-02-26 20:24 UTC by rhdtn311

### 🐕 작업 개요
- closed #39 

### ⚒️ 작업 사항
- 제안 생성 API 를 구현하였습니다

### 📚 참고 자료

### 🧐 고민 해줬으면 하는 점
- `TestUtils`를 여러 클래스로 세분화 하는게 나을까요?

2023-02-27 04:57 UTC, Seongjun-Kwon requested changes
고생 많으셨어요 태현님.. 근사한 코드네요

2023-02-27 04:57 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/heycake/common/exception/ErrorCode.java
> +	DUPLICATED_OFFER(HttpStatus.CONFLICT, "이미 해당 주문에 제안 글을 작성하였습니다."),
주문보다 더 추상화하면 어떨까요?

2023-02-27 04:57 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/heycake/common/mapper/OfferMapper.java
> +@NoArgsConstructor(access = AccessLevel.PRIVATE)
👍

2023-02-27 04:57 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/heycake/domain/offer/controller/OfferController.java
> +			@RequestParam Long memberId) {
이것은 인증 로직이 완료되면 추후에 바뀌는 것이죠?

2023-02-27 04:57 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/heycake/domain/offer/facade/OfferFacade.java
> +	private static final String OFFER_IMAGE_SUB_PATH = "images/offers";
image/offers 인 것으로 알고 있습니다! 👍

2023-02-27 04:57 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/heycake/domain/offer/model/dto/request/OfferSaveRequest.java
> +		MultipartFile offerImage
파일도 @NotNull 해주세요!
dto 단에서 검증된다고 생각하고 null 검증을 따로 안해줬습니다..

2023-02-27 04:57 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/heycake/domain/offer/service/OfferService.java
> +		return offer.getId();
눈이 부셔요

2023-02-27 04:57 UTC, Seongjun-Kwon commented on src/test/java/com/programmers/heycake/domain/offer/controller/OfferControllerTest.java
> +		@DisplayName("Success - 제안 생성에 성공한다. - saveOffer")
Nested 하위 테스트들에는 마지막에 메서드명 빼주는 것으로 알고 있습니다!
아래 테스트들도 적용해주세용!

2023-02-27 04:57 UTC, Seongjun-Kwon commented on src/test/java/com/programmers/heycake/domain/offer/controller/OfferControllerTest.java
> +			assertThat(offers).hasSize(1);
이미 db 에 더미들이 들어가 있으면 1이 아니지 않을 수 있을 것 같아요.
기존 사이즈랑 비교해서 1 늘어난 것을 비교해주는 것은 어떤가요?
아니면 시작 전후에 삭제를 해주는 것도 괜찮을 것 같아요

2023-02-27 04:57 UTC, Seongjun-Kwon commented on src/test/java/com/programmers/heycake/utils/TestUtil.java
> +public class TestUtil {
근사하네요... 이 클래스가 빨리 merge 됐으면 좋겠어요...

2023-02-27 07:58 UTC, goseungwon approved these changes

2023-02-27 07:59 UTC, goseungwon approved these changes
고생하셨습니다!!
testUtils는 현재까진 괜찮아 보이는데 점점 추가되면 너무 커질거같군요!
나중에 도메인별로 분리하는게 좋아보입니다!

2023-03-02 15:31 UTC, BnDC approved these changes

2023-03-02 15:31 UTC, BnDC commented on src/test/java/com/programmers/heycake/utils/TestUtil.java
> +}
테스트 유틸 매우 유용할 거 같네요

2023-03-05 05:56 UTC, closed without merging