Chore: #8 Spring Rest Docs 세팅
prgrms-web-devcourse/Team-07-hey-cake-BE pull request #9
Opened 2023-02-18 17:50 UTC by rhdtn311

### 🐕 작업 개요
closed #8 
- Spring Rest Docs를 사용하여 API를 문서화 하기 위한 초기 세팅 

### ⚒️ 작업 사항
- build.gradle에 Spring Rest Docs 관련 설정 추가
- html 형식의 문서화를 위한 템플릿 샘플 작성

### 📚 참고 자료
- [문서화 노션 링크](https://www.notion.so/Spring-Rest-Docs-491742e47b8f4253a535d9bb3adeae0c)
- [참고1](https://tecoble.techcourse.co.kr/post/2020-08-18-spring-rest-docs/)
- [참고2](https://docs.spring.io/spring-restdocs/docs/current/reference/htmlsingle/)

### 🧐 고민 해줬으면 하는 점

2023-02-19 05:59 UTC, Seongjun-Kwon requested changes

2023-02-19 05:59 UTC, Seongjun-Kwon commented on build.gradle
> +
asciidoctor 설정은 안해줘도 되는 것인가요?

2023-02-20 01:24 UTC, goseungwon approved these changes
고생하셨습니다!

2023-02-20 01:37 UTC, BnDC approved these changes
고생하셨어요

2023-02-20 02:13 UTC, Seongjun-Kwon approved these changes
고생했어요~

2023-02-20 02:13 UTC, merged