Feat: 주문 리스트 조회 API 구현
prgrms-web-devcourse/Team-07-hey-cake-BE pull request #99
Opened 2023-03-03 01:13 UTC by BnDC

### 🐕 작업 개요
- #57

### ⚒️ 작업 사항
- 주문 리스트 조회 기능 구현

2023-03-03 04:49 UTC, goseungwon reviewed
고생하셨습니다!! 
코멘트 확인 부탁드려요~

2023-03-03 04:49 UTC, goseungwon commented on src/main/java/com/programmers/heycake/domain/order/controller/OrderController.java
> +	) {
enum값 외의 다른 값이 들어오거나, 저희가 지정하지 않은 region을 조회하면 어떻게 되죵?🤔

2023-03-03 04:49 UTC, goseungwon commented on src/main/java/com/programmers/heycake/domain/order/model/dto/response/OrderGetSimpleResponses.java
> +		Boolean isLast
isLast field가 필요한 이유가 있을까용?
courSorId를 음수로 보내도 될거라고 생각합니다

2023-03-03 06:28 UTC, Seongjun-Kwon approved these changes
고생하셨습니다

2023-03-03 06:28 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/heycake/common/mapper/OrderMapper.java
> +	public static OrderGetServiceSimpleResponse toOrderGetServiceSimpleResponse(Order order) {
simple 이 의미하는 것이 무엇인가요?

2023-03-03 06:28 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/heycake/domain/order/controller/OrderController.java
> +	) {
region 은 따로 관리해줄 필요가 있겠네요.
Enum 은 MethodArgumentTypeMismatchException 를 잡도록 처리해놨습니다.

2023-03-03 06:28 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/heycake/domain/order/model/dto/response/OrderGetSimpleResponse.java
> +		@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
여기도 승원님 shape  관련 리뷰 반영해주세요

2023-03-03 06:28 UTC, Seongjun-Kwon commented on src/main/java/com/programmers/heycake/domain/order/model/dto/response/OrderGetSimpleResponses.java
> +		Boolean isLast
네 저는 마지막이면 0을 보내도록 처리했어요. 참고해보세용

2023-03-03 08:34 UTC, rhdtn311 requested changes
Date, Time 관련 의도하지 않은 동작이 있을 것 같아서 확인 부탁드립니다.

2023-03-03 08:34 UTC, rhdtn311 commented on src/main/java/com/programmers/heycake/common/mapper/OrderMapper.java
> +						.collect(Collectors.toList())
`toList()`도 됩니다.

2023-03-03 08:34 UTC, rhdtn311 commented on src/main/java/com/programmers/heycake/common/mapper/OrderMapper.java
> +				.visitTime(orderSimpleGetServiceResponse.visitDate())
`visitTime`에 `visitDate()`가 들어가있는데 맞는건가요 ??

2023-03-03 08:34 UTC, rhdtn311 commented on src/main/java/com/programmers/heycake/domain/order/facade/OrderFacade.java
> +	@Transactional
단순 조회로직이라면 `@Transactional(readOnly=true)` 옵션을 붙이는게 좋지 않을까요?

2023-03-03 08:34 UTC, rhdtn311 commented on src/main/java/com/programmers/heycake/domain/order/model/dto/response/OrderGetServiceSimpleResponse.java
> +		LocalDateTime visitDate,
`LocalDateTime` 인데 변수명이 `Date`인게 어색해보여요

2023-03-03 08:34 UTC, rhdtn311 commented on src/main/java/com/programmers/heycake/domain/order/service/OrderService.java
> +				.collect(Collectors.toList());
`toList()`도 가능합니다.

2023-03-03 18:11 UTC, BnDC commented on src/main/java/com/programmers/heycake/common/mapper/OrderMapper.java
> +	public static OrderGetServiceSimpleResponse toOrderGetServiceSimpleResponse(Order order) {
simple은 상세(detail) 조회와 차이를 두기 위해서 추가한 수식어입니다.

2023-03-03 18:14 UTC, BnDC commented on src/main/java/com/programmers/heycake/domain/order/model/dto/response/OrderGetSimpleResponse.java
> +		@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
수정하겠습니다!

2023-03-03 20:02 UTC, BnDC commented on src/main/java/com/programmers/heycake/domain/order/model/dto/response/OrderGetServiceSimpleResponse.java
> +		LocalDateTime visitDate,
이 부분은 `Order` 엔티티의 칼럼 값  `visitDate`을 그대로 사용하고 있습니다. 
`Order`의 엔티티 칼럼 값 수정을 논의해보면 좋을거 같습니다.

2023-03-03 20:11 UTC, BnDC commented on src/main/java/com/programmers/heycake/domain/order/controller/OrderController.java
> +	) {
조건에 맞지 않은 region이 들어오면, 빈 리스트가 반환됩니다. 프론트엔드 개발자 분들이 region의 값을 알고 있어 그 값으로만 요청이 오는것을 상정하고 작성하였습니다.

2023-03-04 06:28 UTC, BnDC commented on src/main/java/com/programmers/heycake/domain/order/model/dto/response/OrderGetSimpleResponses.java
> +		Boolean isLast
프론트분이 react-query를 사용하신다고 하셔서 react-query 페이징 처리에 대해 검색을 해보았는데, 마지막 페이지인지 여부를 나타내주는 boolean 값이 있다는 포스팅을 참고해서 isLast를 추가해 봤습니다. 차후 프론트분이랑 논의해서 유지할지 제거할지 결정할거 같습니다.

2023-03-04 15:49 UTC, goseungwon approved these changes
모두 이유가 있었군요! 고생하셨습니다!!

값 검증을 이중으로 해줄지에 대해서는 고민되는군요

2023-03-04 18:15 UTC, Seongjun-Kwon approved these changes

2023-03-04 18:53 UTC, rhdtn311 approved these changes
👍

2023-03-04 19:19 UTC, merged